### ISSUE TITLE
"Save As" not working when saving new file

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs5#5]
OS: Windows 11 Pro, 22000.675
Using the Save As function to save a sheet  to a file which does not already exist simply does not produce a new file.
Saving to a blank but existing file also does not work.

**Comment by richardwilkes** [comment]
I'm not seeing any problem, but I've also not tried it on Windows recently. Is there some log output? If so, copy & paste it here, please.

**Comment by rinickolous** [comment]
Sure thing. How do I access the log?

**Comment by richardwilkes** [comment]
If you run with the `-h` option, you'll see info about where the log file is written. Alternately, you can just run with the `--log-to-console` option and reproduce the error and any logging should show up on the console you launched it from.

**Comment by rinickolous** [comment]
I'm not sure if this will be any help. I opened the program, opened a file, and tried to Save As. Attached below are my logs
[gcs.log](https://github.com/richardwilkes/gcs5/files/8873408/gcs.log)

**Comment by richardwilkes** [comment]
Thanks. I see a panic being generated from the menu code in the logs, which is useful -- but perhaps not for this particular issue. Anyway, will take a look and see.

**Comment by richardwilkes** [comment]
OK, should be fixed in the latest source. Stupid mistake on my part. Worse, when I tested for it locally, I was running the wrong binary, which explains why I never saw the issue.
