### ISSUE TITLE
Suggestion: Add Arrow/Navigation Keys to List of Rebindable Keys

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs5#7]
Honestly I'm driven to make this suggestion by my desire to be able to set everything to vim keys

**Comment by richardwilkes** [comment]
Could you elaborate on this a bit? My initial reaction is just “no”… but willing to revise my opinion if there is a good justification.

**Comment by rinickolous** [comment]
Eh, it would be something only a small number of userd (maybe just me) would find useful, so if it'd take any significant effort to implement then don't bother
